require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp" 
require "user.dap"
require "user.telescope" 
require "user.autopairs"
require "user.treesitter"
require "user.bufferline"
require "user.comment"
require "user.lualine"
require "user.nvim-tree"
require "user.toggleterm"
require "user.project"
--require "user.gitsigns"
require "user.neogit"
require "user.keymaps"
require "user.autocommands"

--require "user.impatient" -- de momento no lo necesito
--require "user.indentline"
--require "user.alpha" -- no necesario -> dashboard
--require "user.whichkey"
